version: '3.8'

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
      
  

  orogen_data:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:5000'
      - '80:5000'
    environment:
      - MONGO_URL=mongodb://mongo_db:27017
      - MONGO_DB=vifta
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}